### ISSUE TITLE
Add Team members and little bit of their background information to org Readme

### ISSUE THREAD

**Issue by inson1** [FossifyOrg/.github#5]
From https://github.com/FossifyOrg/General-Discussion/issues/16

1. It would be nice imo
2. We should do it anyway for the website, after this its just copy and paste
3. I think its important to be transparent, so I woud add part that naveensingh was paid freelance dev at SMT.

@Aga-C you could say also add something

@naveensingh something to add?

> I have been doing contract-based work for years. Mostly Android development, Python, and sometimes machine learning. At other times, I play with my things which includes building drones, planes from scratch, 3d printers, distro-hopping, etc.
> 
Why did you create the fork?
> 
> Simply to keep the project open source and alive and also because I like the idea of feature-complete open-source apps that are as reliable as their closed-source counterparts.

**Comment by naveensingh** [comment]
No, I want to keep it short. This info is more suited for the website's about page. Closing...

**Comment by inson1** [comment]
@naveensingh it could be in details tag

**Comment by kwxmxb** [comment]
I want to add Chinese language support to the www.fossify.org website.  

What should I do?
